controller_manager:
  ros__parameters:
    update_rate: 5000

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_a
      - joint_b
      - joint_c
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity